version: "3.9"
services:
  kong-db:
    container_name: kong-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong-user
      POSTGRES_PASSWORD: kong-password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  default:
    name: kong-network
