version: "3.9"
services:
  kong:
    container_name: kong
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong-user
      KONG_PG_PASSWORD: kong-password
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    volumes:
      - ./kong-log:/usr/local/kong/logs

  konga:
    depends_on:
      - kong
    container_name: konga
    image: pantsel/konga:latest
    environment:
      NODE_ENV: production
      TOKEN_SECRET: password
    ports:
      - "1337:1337"

  echo:
    container_name: echo
    image: echo:1.0.0
    ports:
      - "3000:3000"

networks:
  default:
    name: kong-network